### ISSUE TITLE
Return at end of content causes issues

### ISSUE THREAD

**Issue by pilar1347** [Vizir/ng-contenteditable#9]
I'm seeing this in example 2 here: http://vizir.github.io/ng-contenteditable/

On PC Chrome (Version 55.0.2883.87) when return is pressed at the end of the line, the cursor jumps back to the beginning of the string and starts typing backwards.

**Comment by erikshestopal** [comment]
I am also seeing this issue happen as well @pilar1347. Any update on how to resolve this issue?

**Comment by pilar1347** [comment]
@thisiserik I ended up not using this library. Instead I'm just binding the html to the contenteditable div and updating the model manually on blur, alternatively you could also update on keyup. Might not be the best solution, but it's working for me. See CodePen: http://codepen.io/anon/pen/qReKGM

**Comment by FabricioFFC** [comment]
@pilar1347 and @thisiserik the version 0.0.5 fix this issue. Sorry for the delay.
